import React, { useState } from 'react'
import { generateCourseOutline, generateCourseOutlineFromFile } from '../../api/aiApi'
import { useCourseEditorStore } from '../../store/use-course-editor-store'

const AIAssistantPanel: React.FC = () => {
  const updateCourse = useCourseEditorStore((state) => state.updateCourse)
  const addSection = useCourseEditorStore((state) => state.addSection)
  const updateSection = useCourseEditorStore((state) => state.updateSection)
  const addPage = useCourseEditorStore((state) => state.addPage)
  const updatePage = useCourseEditorStore((state) => state.updatePage)

  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [successMessage, setSuccessMessage] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [courseTitle, setCourseTitle] = useState('')
  const [courseDescription, setCourseDescription] = useState('')
  const [targetAudience, setTargetAudience] = useState('')
  const [audienceProficiencyLevel, setAudienceProficiencyLevel] = useState('Beginner')
  const [duration, setDuration] = useState('2 hours')
  const [language, setLanguage] = useState('Vietnamese')
  const [learningOutcomes, setLearningOutcomes] = useState('')
  const [prerequisites, setPrerequisites] = useState('')
  const [additionalInstructions, setAdditionalInstructions] = useState('')
  const [referenceFile, setReferenceFile] = useState<File | null>(null)

  const resetAssistantForm = () => {
    setCourseTitle('')
    setCourseDescription('')
    setTargetAudience('')
    setAudienceProficiencyLevel('Beginner')
    setDuration('2 hours')
    setLanguage('Vietnamese')
    setLearningOutcomes('')
    setPrerequisites('')
    setAdditionalInstructions('')
    setReferenceFile(null)
    setError(null)
    setLoading(false)
  }

  const applyOutlineToEditor = (outline: {
    title: string
    description: string
    sections: Array<{ title: string; topics: string[] }>
  }) => {
    updateCourse({ title: outline.title || 'AI Generated Course', description: outline.description || '' })

    outline.sections.forEach((sectionData, index) => {
      addSection()
      const stateAfterAddSection = useCourseEditorStore.getState()
      const sectionId = stateAfterAddSection.sectionOrder[stateAfterAddSection.sectionOrder.length - 1]
      if (!sectionId) return

      updateSection(sectionId, {
        title: sectionData.title || `Section ${index + 1}`,
        description: `Generated by AI for ${courseTitle || courseDescription || 'your course'}`
      })

      const firstPageId = stateAfterAddSection.pageOrder[sectionId]?.[0]
      if (firstPageId && sectionData.topics[0]) {
        updatePage(firstPageId, { title: sectionData.topics[0], type: 'content' })
      }

      sectionData.topics.slice(1).forEach((topicTitle) => {
        addPage(sectionId, 'content')
        const latestState = useCourseEditorStore.getState()
        const newPageId = latestState.pageOrder[sectionId]?.[latestState.pageOrder[sectionId].length - 1]
        if (newPageId) {
          updatePage(newPageId, { title: topicTitle || 'New Topic', type: 'content' })
        }
      })
    })
  }

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!courseDescription.trim() || !courseTitle.trim() || !learningOutcomes.trim()) {
      setError('Vui lòng nhập Course title, Course description và Learning outcomes.')
      return
    }

    setSuccessMessage(null)
    setError(null)
    setLoading(true)
    try {
      const payload = {
        courseTitle: courseTitle.trim(),
        courseDescription: courseDescription.trim(),
        targetAudience: targetAudience.trim() || 'General learners',
        audienceProficiencyLevel: audienceProficiencyLevel.trim() || 'Beginner',
        duration: duration.trim() || '2 hours',
        language: language.trim() || 'Vietnamese',
        learningOutcomes: learningOutcomes.trim(),
        prerequisites: prerequisites.trim() || 'Không yêu cầu',
        additionalInstructions: additionalInstructions.trim() || undefined
      }

      const outline = referenceFile
        ? await generateCourseOutlineFromFile(referenceFile, payload)
        : await generateCourseOutline(payload)

      applyOutlineToEditor(outline)
      resetAssistantForm()
      setSuccessMessage('Đã tạo outline và thêm vào course.')
      setOpen(false)
    } catch {
      setError('Không thể gọi AI. Vui lòng thử lại.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className='pointer-events-none fixed bottom-5 right-5 z-40'>
      {successMessage ? (
        <div className='pointer-events-auto mb-3 w-[360px] rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-700 shadow'>
          <div className='flex items-center justify-between gap-2'>
            <span>{successMessage}</span>
            <button
              type='button'
              onClick={() => setSuccessMessage(null)}
              className='text-xs text-emerald-700/80 hover:text-emerald-900'
            >
              Đóng
            </button>
          </div>
        </div>
      ) : null}
      {open ? (
        <div className='pointer-events-auto w-[360px] rounded-2xl border border-violet-200 bg-white shadow-2xl'>
          <div className='flex items-center justify-between rounded-t-2xl bg-violet-600 px-4 py-3 text-white'>
            <div>
              <p className='text-sm font-semibold'>AI Assistant</p>
              <p className='text-xs text-violet-100'>Tạo gợi ý bài giảng tự động</p>
            </div>
            <button
              type='button'
              onClick={() => {
                setOpen(false)
                if (!loading) resetAssistantForm()
              }}
              className='rounded-md bg-white/10 px-2 py-1 text-xs hover:bg-white/20'
            >
              Thu gọn
            </button>
          </div>

          <form onSubmit={onSubmit} className='space-y-3 p-4'>
            <input
              value={courseTitle}
              onChange={(e) => setCourseTitle(e.target.value)}
              placeholder='Course title *'
              className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
            />
            <textarea
              value={courseDescription}
              onChange={(e) => setCourseDescription(e.target.value)}
              rows={3}
              placeholder='Course description *'
              className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
            />
            <input
              value={targetAudience}
              onChange={(e) => setTargetAudience(e.target.value)}
              placeholder='Target audience'
              className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
            />
            <div className='grid grid-cols-2 gap-2'>
              <input
                value={audienceProficiencyLevel}
                onChange={(e) => setAudienceProficiencyLevel(e.target.value)}
                placeholder='Proficiency level'
                className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
              />
              <input
                value={duration}
                onChange={(e) => setDuration(e.target.value)}
                placeholder='Duration'
                className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
              />
            </div>
            <textarea
              value={learningOutcomes}
              onChange={(e) => setLearningOutcomes(e.target.value)}
              rows={2}
              placeholder='Learning outcomes *'
              className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
            />
            <textarea
              value={prerequisites}
              onChange={(e) => setPrerequisites(e.target.value)}
              rows={2}
              placeholder='Prerequisites'
              className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
            />
            <input
              value={language}
              onChange={(e) => setLanguage(e.target.value)}
              placeholder='Language'
              className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
            />
            <textarea
              value={additionalInstructions}
              onChange={(e) => setAdditionalInstructions(e.target.value)}
              rows={2}
              placeholder='Additional instructions (optional)'
              className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
            />
            <div>
              <input
                type='file'
                accept='.pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain'
                onChange={(e) => setReferenceFile(e.target.files?.[0] || null)}
                className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm file:mr-3 file:rounded-md file:border-0 file:bg-violet-50 file:px-2 file:py-1 file:text-violet-700'
              />
              {referenceFile ? <p className='mt-1 text-xs text-gray-500'>File: {referenceFile.name}</p> : null}
            </div>

            {error && <p className='text-xs text-red-600'>{error}</p>}

            <button
              type='submit'
              disabled={loading}
              className='w-full rounded-lg bg-violet-600 px-3 py-2 text-sm font-medium text-white disabled:opacity-60'
            >
              {loading ? 'Đang tạo...' : referenceFile ? 'Tạo từ file + AI' : 'Hỏi AI tạo bài giảng'}
            </button>
          </form>
        </div>
      ) : (
        <button
          type='button'
          onClick={() => setOpen(true)}
          className='pointer-events-auto rounded-full bg-violet-600 px-4 py-3 text-sm font-medium text-white shadow-lg hover:bg-violet-700'
        >
          ✨ Mở AI
        </button>
      )}
    </div>
  )
}

export default AIAssistantPanel
