import React, { useState } from 'react'
import { generateCourseOutline } from '../../api/aiApi'
import { useCourseEditorStore } from '../../store/use-course-editor-store'

const AIAssistantPanel: React.FC = () => {
  const updateCourse = useCourseEditorStore((state) => state.updateCourse)
  const addSection = useCourseEditorStore((state) => state.addSection)
  const updateSection = useCourseEditorStore((state) => state.updateSection)
  const addPage = useCourseEditorStore((state) => state.addPage)
  const updatePage = useCourseEditorStore((state) => state.updatePage)

  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [topic, setTopic] = useState('')
  const [targetAudience, setTargetAudience] = useState('')
  const [language, setLanguage] = useState('Vietnamese')
  const [numberOfSections, setNumberOfSections] = useState(5)
  const [additionalInstructions, setAdditionalInstructions] = useState('')

  const resetAssistantForm = () => {
    setTopic('')
    setTargetAudience('')
    setLanguage('Vietnamese')
    setNumberOfSections(5)
    setAdditionalInstructions('')
    setError(null)
    setLoading(false)
  }

  const applyOutlineToEditor = (outline: {
    title: string
    description: string
    sections: Array<{ title: string; topics: string[] }>
  }) => {
    updateCourse({ title: outline.title || 'AI Generated Course', description: outline.description || '' })

    outline.sections.forEach((sectionData, index) => {
      addSection()
      const stateAfterAddSection = useCourseEditorStore.getState()
      const sectionId = stateAfterAddSection.sectionOrder[stateAfterAddSection.sectionOrder.length - 1]
      if (!sectionId) return

      updateSection(sectionId, {
        title: sectionData.title || `Section ${index + 1}`,
        description: `Generated by AI for ${topic}`
      })

      const firstPageId = stateAfterAddSection.pageOrder[sectionId]?.[0]
      if (firstPageId && sectionData.topics[0]) {
        updatePage(firstPageId, { title: sectionData.topics[0], type: 'content' })
      }

      sectionData.topics.slice(1).forEach((topicTitle) => {
        addPage(sectionId, 'content')
        const latestState = useCourseEditorStore.getState()
        const newPageId = latestState.pageOrder[sectionId]?.[latestState.pageOrder[sectionId].length - 1]
        if (newPageId) {
          updatePage(newPageId, { title: topicTitle || 'New Topic', type: 'content' })
        }
      })
    })
  }

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!topic.trim()) {
      setError('Vui lòng nhập chủ đề khóa học.')
      return
    }

    setError(null)
    setLoading(true)
    try {
      const outline = await generateCourseOutline({
        topic: topic.trim(),
        targetAudience: targetAudience.trim() || 'General learners',
        language: language.trim() || 'Vietnamese',
        numberOfSections,
        additionalInstructions: additionalInstructions.trim() || undefined
      })
      applyOutlineToEditor(outline)
      resetAssistantForm()
      setOpen(false)
    } catch {
      setError('Không thể gọi AI. Vui lòng thử lại.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className='pointer-events-none fixed bottom-5 right-5 z-40'>
      {open ? (
        <div className='pointer-events-auto w-[360px] rounded-2xl border border-violet-200 bg-white shadow-2xl'>
          <div className='flex items-center justify-between rounded-t-2xl bg-violet-600 px-4 py-3 text-white'>
            <div>
              <p className='text-sm font-semibold'>AI Assistant</p>
              <p className='text-xs text-violet-100'>Tạo gợi ý bài giảng tự động</p>
            </div>
            <button
              type='button'
              onClick={() => {
                setOpen(false)
                if (!loading) resetAssistantForm()
              }}
              className='rounded-md bg-white/10 px-2 py-1 text-xs hover:bg-white/20'
            >
              Thu gọn
            </button>
          </div>

          <form onSubmit={onSubmit} className='space-y-3 p-4'>
            <input
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder='Chủ đề khóa học (vd: React cơ bản)'
              className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
            />
            <input
              value={targetAudience}
              onChange={(e) => setTargetAudience(e.target.value)}
              placeholder='Đối tượng học viên'
              className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
            />
            <input
              value={language}
              onChange={(e) => setLanguage(e.target.value)}
              placeholder='Ngôn ngữ'
              className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
            />
            <input
              type='number'
              min={1}
              max={12}
              value={numberOfSections}
              onChange={(e) => setNumberOfSections(Number(e.target.value) || 1)}
              className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
            />
            <textarea
              value={additionalInstructions}
              onChange={(e) => setAdditionalInstructions(e.target.value)}
              rows={3}
              placeholder='Yêu cầu thêm (không bắt buộc)'
              className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-200'
            />

            {error && <p className='text-xs text-red-600'>{error}</p>}

            <button
              type='submit'
              disabled={loading}
              className='w-full rounded-lg bg-violet-600 px-3 py-2 text-sm font-medium text-white disabled:opacity-60'
            >
              {loading ? 'Đang tạo...' : 'Hỏi AI tạo bài giảng'}
            </button>
          </form>
        </div>
      ) : (
        <button
          type='button'
          onClick={() => setOpen(true)}
          className='pointer-events-auto rounded-full bg-violet-600 px-4 py-3 text-sm font-medium text-white shadow-lg hover:bg-violet-700'
        >
          ✨ Mở AI
        </button>
      )}
    </div>
  )
}

export default AIAssistantPanel
